#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity/3.6.3
fi

VERSION=0.22.3
PACKAGE=bismark
TOOL=bismark_methylation_extractor
DIRECTORY=/opt/packages/$PACKAGE/$VERSION

singularity exec -B /pylon5 $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
